keys:
  - &admin age1w7stgltn2stl94ap045qrzufmy9x9wuqnzrlug60v58g5j8m6c3qym8uxy
  # Teachers
  - &larsgunnar age1w7stgltn2stl94ap045qrzufmy9x9wuqnzrlug60v58g5j8m6c3qym8uxy
  # Students
  - &paco age1afv4svstg2dc8mr49qf8hq5xj7gfm2gfaagdhucgrfnjkj50se8s8wj3kd
  - &lillian age1ncxfpn9uy6mnxjephpnu4p7lrfxx4xusadmytdj3qyevdlvg3e0q3r5pgn

creation_rules:
  # Production secrets
  - path_regex: secrets/api-keys.yaml
    key_groups:
      - age:
          - *admin
          - *larsgunnar
  # Development SSH Key
  - path_regex: secrets/debug_key
    key_groups:
      - age:
          - *admin
          - *larsgunnar
          - *paco
          - *lillian
