keys:
  - &admin age1w7stgltn2stl94ap045qrzufmy9x9wuqnzrlug60v58g5j8m6c3qym8uxy
  # Teachers
  - &larsgunnar age1w7stgltn2stl94ap045qrzufmy9x9wuqnzrlug60v58g5j8m6c3qym8uxy
  # Students

creation_rules:
  # Production secrets
  - path_regex: secrets/api-keys.yaml
    key_groups:
      - age:
          - *admin
          - *larsgunnar
