services:
  # Entrypoint for external users
  ingress:
    container_name: "traefik"
    image: "traefik:v3.4"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "//var/run/docker.sock:/var/run/docker.sock:ro"

  # Our own service
  example-service:
    container_name: "example.service"
    image: ghcr.io/larsgjobloop/gitops-lite/example-service:2825eef49dac29fd80f103fe398896d67d6fb55a
    environment:
      DATABASE_CONNECTIONSTRING: "postgresql://myuser:mypassword@localhost:5432/mydatabase"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.example-service.entrypoints=web"
      - "traefik.http.routers.example-service.rule=PathPrefix(`/api/example`)"
      - "traefik.http.middlewares.example-service.stripprefix.prefixes=/api/example"
      - "traefik.http.routers.example-service.middlewares=example-service"
      - "traefik.http.services.example-service.loadbalancer.server.port=8080"
