services:
  ingress:
    container_name: "traefik"
    image: "traefik:v3.4"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80" # Available at http://localhost
      - "8080:8080" # Admin UI. Available at http://localhost:8080
    volumes:
      # - "/var/run/docker.sock:/var/run/docker.sock:ro" # Linux
      - "//var/run/docker.sock:/var/run/docker.sock:ro" # Windows

  object-storage:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000" # S3 API port
      - "9001:9001" # MinIO Console port/Web UI
    volumes:
      - ~/minio/data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"
    restart: unless-stopped
