services:
  ingress:
    container_name: "traefik"
    image: "traefik:v3.4"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80" # Available at http://localhost
      - "8080:8080" # Admin UI. Available at http://localhost:8080
    volumes:
      # - "/var/run/docker.sock:/var/run/docker.sock:ro" # Linux
      - "//var/run/docker.sock:/var/run/docker.sock:ro" # Windows

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=PathPrefix('/whoami')"
      - "traefik.http.routers.whoami.entrypoints=web"
